name: Load Environment Variables from YAML file

on: [ push ]

jobs:
  call_node_workflow:
    uses: ./.github/workflows/set_variables.yaml

  load_vars:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g yaml |
          npm install @aml-org/als-server
          
      - name: Check installed dependencies
        run: |
          npm list
